import { PATH, ROLE, STATUS } from './constants.js';
import { makeBankLine, makeLegalDocuments, makeTaxDocuments } from './masterData.js';

/**
 * Data contoh untuk demo front-end. Tidak ada backend:
 * seluruh state hidup di memori selama sesi berlangsung.
 * Sengaja mencakup setiap status lifecycle agar tiap layar bisa diuji.
 */

const daysAgo = (n) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const INTERNAL_USERS = [
  {
    id: 'usr-staff-1',
    name: 'Dewi Anggraini',
    email: 'dewi.anggraini@paragon-corp.com',
    role: ROLE.STAFF,
  },
  {
    id: 'usr-admin-1',
    name: 'Rangga Prasetyo',
    email: 'rangga.prasetyo@paragon-corp.com',
    role: ROLE.ADMIN,
  },
  {
    id: 'usr-manager-1',
    name: 'Lestari Handayani',
    email: 'lestari.handayani@paragon-corp.com',
    role: ROLE.MANAGER,
  },
];

const emptyTax = () => ({
  taxName: '',
  taxAddress: '',
  nik: '',
  npwp: '',
  ktpDocument: null,
  npwpDocument: null,
  transactionType: '',
  tin: '',
  tinDocument: null,
  brn: '',
  brnDocument: null,
  gstNumber: '',
  documents: makeTaxDocuments(),
});

const emptyProfile = () => ({
  tax: emptyTax(),
  documents: { ...makeLegalDocuments(), reasonNoDoe: '' },
  licenses: {
    gmp: { number: '', expiryDate: '', file: null, notApplicable: false },
    cpkb: { number: '', expiryDate: '', file: null, notApplicable: false },
    halal: { number: '', expiryDate: '', file: null, notApplicable: false },
  },
  banking: {
    currency: 'IDR',
    setAgreementRate: '',
    termsOfPayment1: '',
    termsOfPayment2: '',
    termsOfPayment3: '',
    fiscalPosition: '',
    lines: [makeBankLine()],
  },
  contacts: [],
  completed: { tax: false, documents: false, licenses: false, banking: false, contacts: false },
});

const filledProfile = (overrides = {}) => ({
  ...emptyProfile(),
  tax: {
    taxName: 'PT Sumber Makmur Sejahtera',
    taxAddress: 'Jl. Industri Raya No. 45, Cikarang Utara, Bekasi 17530',
    nik: '3175094401900002',
    npwp: '0123456789012345',
    ktpDocument: { name: 'ktp-direktur.pdf', size: 842_112, type: 'application/pdf' },
    npwpDocument: { name: 'npwp-perusahaan.pdf', size: 640_000, type: 'application/pdf' },
    transactionType: 'T01',
    tin: 'TIN-2026-004512',
    tinDocument: { name: 'dokumen.pdf', size: 842_112, type: 'application/pdf' },
    brn: 'BRN-880231-K',
    brnDocument: { name: 'dokumen.pdf', size: 842_112, type: 'application/pdf' },
    gstNumber: 'GST-0099-2026',
    documents: {
      ...makeTaxDocuments(),
      siup: {
        number: 'SIUP-503/2026',
        file: { name: 'siup-2026.pdf', size: 1_204_880, type: 'application/pdf' },
        validFrom: '2026-01-01',
        validUntil: '2029-12-31',
      },
      pkp: {
        number: 'PKP-77120',
        file: { name: 'dokumen.pdf', size: 842_112, type: 'application/pdf' },
        validFrom: '2026-02-01',
        validUntil: '2028-01-31',
      },
    },
  },
  documents: {
    ...makeLegalDocuments(),
    aktaPendirian: { name: 'akta-pendirian.pdf', size: 1_640_320, type: 'application/pdf' },
    skPendirian: { name: 'sk-kemenkumham.pdf', size: 986_112, type: 'application/pdf' },
    aktaPerubahan: { name: 'akta-perubahan-2025.pdf', size: 820_000, type: 'application/pdf' },
    nib: { name: 'nib-oss.pdf', size: 742_400, type: 'application/pdf' },
    suratIzinUsaha: { name: 'sertifikat-standar.pdf', size: 610_000, type: 'application/pdf' },
    conflictOfInterest: { name: 'conflict-of-interest.pdf', size: 340_000, type: 'application/pdf' },
    businessLicense: { name: 'business-license.pdf', size: 520_000, type: 'application/pdf' },
    reasonNoDoe: 'Perusahaan berdiri sebelum ketentuan DoE berlaku, dokumen setara terlampir pada akta pendirian.',
  },
  licenses: {
    gmp: { number: 'GMP-2025-8841', expiryDate: '2028-03-31', file: { name: 'gmp.pdf', size: 512_000, type: 'application/pdf' }, notApplicable: false },
    cpkb: { number: '', expiryDate: '', file: null, notApplicable: true },
    halal: { number: 'ID-HAL-77120', expiryDate: '2027-11-20', file: { name: 'halal.pdf', size: 623_104, type: 'application/pdf' }, notApplicable: false },
  },
  banking: {
    currency: 'IDR',
    setAgreementRate: 'active',
    termsOfPayment1: 'D045',
    termsOfPayment2: '',
    termsOfPayment3: '',
    fiscalPosition: 'FP04',
    lines: [
      makeBankLine({
        accountType: 'AT02',
        bankCode: 'BMRI',
        accountNumber: '1370011223344',
        accountHolder: 'PT Sumber Makmur Sejahtera',
        statement: { name: 'rekening-koran.pdf', size: 480_000, type: 'application/pdf' },
      }),
    ],
  },
  contacts: [
    {
      id: 'ct-1',
      name: 'Rina Wulandari',
      title: 'Madam',
      jobPosition: 'Sales',
      email: 'rina.w@sumbermakmur.co.id',
      phone: '(021) 555-2211',
      mobile: '+62 813-1122-3344',
      notes: 'Kontak utama untuk penawaran harga.',
      isPrimary: true,
    },
  ],
  completed: { tax: true, documents: true, licenses: true, banking: true, contacts: true },
  ...overrides,
});

export const SUBMISSIONS = [
  {
    id: 'SUP-2026-0148',
    status: STATUS.SUPPLIER_REQUEST,
    submittedAt: daysAgo(2),
    general: {
      legalStatus: 'Z2',
      entityType: '0001',
      vendorName: 'PT Sumber Makmur Sejahtera',
      vendorType: '0001',
      vendorTypeDetail: '0003',
      targetCompanies: ['Paragon Corp Indonesia'],
      otvStatus: 'C1',
      vendorDirectType: 'Z002',
      companyEmail: 'procurement@sumbermakmur.co.id',
      officePhone: '(021) 555-2210',
      mobilePhone: '+62 812-3456-7890',
      website: 'https://www.sumbermakmur.co.id',
    },
    address: {
      street: 'Jl. Industri Raya No. 45, Kawasan Industri Jababeka',
      country: 'Indonesia',
      province: 'Jawa Barat',
      city: 'Bekasi',
      district: 'Cikarang Utara',
      subdistrict: 'Cibatu',
      postalCode: '17530',
    },
    contact: {
      name: 'Rina Wulandari',
      title: 'Madam',
      jobPosition: 'Sales',
      email: 'rina.w@sumbermakmur.co.id',
      phone: '(021) 555-2211',
      mobile: '+62 813-1122-3344',
      notes: 'Sudah menjadi mitra distribusi informal selama dua tahun.',
    },
    onboardingPath: null,
    account: null,
    profile: emptyProfile(),
    consent: null,
    verification: null,
    timeline: [{ at: daysAgo(2), label: 'Registrasi dikirim pemasok', actor: 'Rina Wulandari' }],
  },
  {
    id: 'SUP-2026-0149',
    status: STATUS.SUPPLIER_REQUEST,
    submittedAt: daysAgo(1),
    general: {
      legalStatus: 'Z2',
      entityType: '0002',
      vendorName: 'CV Kemasan Nusantara',
      vendorType: '0002',
      vendorTypeDetail: '0001',
      targetCompanies: ['Paragon Corp Indonesia', 'Paragon Corp Malaysia'],
      otvStatus: 'C1',
      vendorDirectType: 'Z002',
      companyEmail: 'info@kemasannusantara.com',
      officePhone: '(022) 420-1188',
      mobilePhone: '+62 811-2233-4455',
      website: 'https://www.kemasannusantara.com',
    },
    address: {
      street: 'Jl. Soekarno Hatta No. 210',
      country: 'Indonesia',
      province: 'Jawa Barat',
      city: 'Bandung',
      district: 'Buahbatu',
      subdistrict: 'Sekejati',
      postalCode: '40235',
    },
    contact: {
      name: 'Ahmad Fauzi',
      title: 'Mr',
      jobPosition: 'Finance',
      email: 'ahmad.f@kemasannusantara.com',
      phone: '(022) 420-1189',
      mobile: '+62 812-9988-7766',
      notes: '',
    },
    onboardingPath: null,
    account: null,
    profile: emptyProfile(),
    consent: null,
    verification: null,
    timeline: [{ at: daysAgo(1), label: 'Registrasi dikirim pemasok', actor: 'Ahmad Fauzi' }],
  },
  {
    id: 'SUP-2026-0142',
    status: STATUS.APPROVED,
    submittedAt: daysAgo(9),
    decidedAt: daysAgo(7),
    general: {
      legalStatus: 'Z2',
      entityType: '0004',
      vendorName: 'Golden Ingredients Sdn Bhd',
      vendorType: '0001',
      vendorTypeDetail: '0003',
      targetCompanies: ['Paragon Corp Malaysia'],
      otvStatus: 'C1',
      vendorDirectType: 'Z002',
      companyEmail: 'sales@goldeningredients.my',
      officePhone: '(03) 7890-1122',
      mobilePhone: '+60 12-345 6789',
      website: 'https://www.goldeningredients.my',
    },
    address: {
      street: 'Lot 8, Jalan Perindustrian 3, Kawasan Perindustrian Bukit Rimau',
      country: 'Malaysia',
      province: 'Selangor',
      city: 'Shah Alam',
      district: '',
      subdistrict: '',
      postalCode: '40460',
    },
    contact: {
      name: 'Lee Wei Ming',
      title: 'Mr',
      jobPosition: 'Sales',
      email: 'wei.ming@goldeningredients.my',
      phone: '(03) 7890-1123',
      mobile: '+60 17-234 5678',
      notes: '',
    },
    onboardingPath: null,
    account: null,
    profile: emptyProfile(),
    consent: null,
    verification: null,
    timeline: [
      { at: daysAgo(9), label: 'Registrasi dikirim pemasok', actor: 'Lee Wei Ming' },
      { at: daysAgo(7), label: 'Registrasi disetujui', actor: 'Dewi Anggraini' },
    ],
  },
  {
    id: 'SUP-2026-0139',
    status: STATUS.REJECTED,
    submittedAt: daysAgo(21),
    decidedAt: daysAgo(19),
    rejectReason:
      'Dokumen NPWP tidak sesuai dengan nama pendaftar. Mohon ajukan ulang setelah dokumen diperbarui.',
    general: {
      legalStatus: 'Z1',
      entityType: '',
      vendorName: 'UD Cipta Boga',
      vendorType: '0003',
      vendorTypeDetail: '0004',
      targetCompanies: ['Paragon Corp Indonesia'],
      otvStatus: 'C0',
      vendorDirectType: 'Z002',
      companyEmail: 'ciptaboga@gmail.com',
      officePhone: '',
      mobilePhone: '+62 815-6677-8899',
      website: '',
    },
    address: {
      street: 'Jl. Melati No. 12',
      country: 'Indonesia',
      province: 'Jawa Tengah',
      city: 'Semarang',
      district: 'Banyumanik',
      subdistrict: 'Srondol Wetan',
      postalCode: '50136',
    },
    contact: {
      name: 'Budi Santoso',
      title: 'Mr',
      jobPosition: 'Other',
      email: 'budi.s@gmail.com',
      phone: '',
      mobile: '+62 815-6677-8899',
      notes: '',
    },
    onboardingPath: null,
    account: null,
    profile: emptyProfile(),
    consent: null,
    verification: null,
    timeline: [
      { at: daysAgo(21), label: 'Registrasi dikirim pemasok', actor: 'Budi Santoso' },
      { at: daysAgo(19), label: 'Registrasi ditolak', actor: 'Dewi Anggraini' },
    ],
  },
  {
    id: 'SUP-2026-0135',
    status: STATUS.QUALIFICATION,
    submittedAt: daysAgo(14),
    decidedAt: daysAgo(12),
    onboardingPath: PATH.INTERNAL,
    documentSource: 'whatsapp',
    internalDraft: {
      startedAt: daysAgo(11),
      completedAt: daysAgo(3),
      filledBy: 'Rangga Prasetyo',
    },
    general: {
      legalStatus: 'Z2',
      entityType: '0001',
      vendorName: 'PT Aroma Esensia Nusantara',
      vendorType: '0001',
      vendorTypeDetail: '0003',
      targetCompanies: ['Paragon Corp Indonesia'],
      otvStatus: 'C1',
      vendorDirectType: 'Z002',
      companyEmail: 'halo@aromaesensia.co.id',
      officePhone: '(0341) 556-7788',
      mobilePhone: '+62 813-5566-7788',
      website: 'https://www.aromaesensia.co.id',
    },
    address: {
      street: 'Jl. Raya Karanglo No. 77',
      country: 'Indonesia',
      province: 'Jawa Timur',
      city: 'Malang',
      district: 'Singosari',
      subdistrict: 'Banjararum',
      postalCode: '65153',
    },
    contact: {
      name: 'Sekar Ayu Pratiwi',
      title: 'Madam',
      jobPosition: 'Sales',
      email: 'sekar@aromaesensia.co.id',
      phone: '(0341) 556-7789',
      mobile: '+62 813-5566-7788',
      notes: 'Dokumen dikirim melalui WhatsApp ke admin procurement.',
    },
    account: null,
    profile: filledProfile({
      banking: {
          currency: 'IDR',
          setAgreementRate: 'active',
          termsOfPayment1: 'D045',
          termsOfPayment2: '',
          termsOfPayment3: '',
          fiscalPosition: 'FP04',
          lines: [
            makeBankLine({
              accountType: 'AT02',
              bankCode: 'BCA',
              accountNumber: '0451122334',
              accountHolder: 'PT Aroma Esensia Nusantara',
              statement: { name: 'rekening-koran.pdf', size: 480_000, type: 'application/pdf' },
            }),
          ],
        },
    }),
    consent: null,
    verification: null,
    timeline: [
      { at: daysAgo(14), label: 'Registrasi dikirim pemasok', actor: 'Sekar Ayu Pratiwi' },
      { at: daysAgo(12), label: 'Registrasi disetujui', actor: 'Dewi Anggraini' },
      { at: daysAgo(11), label: 'Jalur registrasi internal dipilih', actor: 'Rangga Prasetyo' },
      { at: daysAgo(3), label: 'Registrasi internal selesai, akun dikirim', actor: 'Rangga Prasetyo' },
      { at: daysAgo(2), label: 'Dokumen lolos periksa, lanjut ke qualification', actor: 'Dewi Anggraini' },
    ],
  },
  {
    id: 'SUP-2026-0131',
    status: STATUS.REGISTRATION,
    submittedAt: daysAgo(24),
    decidedAt: daysAgo(22),
    onboardingPath: PATH.INVITE,
    account: {
      accountId: 'SUP-PAC-0131',
      inviteToken: 'pgn-inv-4b21fa',
      emailSentAt: daysAgo(18),
      passwordChanged: true,
    },
    general: {
      legalStatus: 'Z2',
      entityType: '0001',
      vendorName: 'PT Karton Sejati Abadi',
      vendorType: '0002',
      vendorTypeDetail: '0002',
      targetCompanies: ['Paragon Corp Indonesia'],
      otvStatus: 'C1',
      vendorDirectType: 'Z002',
      companyEmail: 'procurement@kartonsejati.co.id',
      officePhone: '(024) 760-3345',
      mobilePhone: '+62 817-4455-6677',
      website: 'https://www.kartonsejati.co.id',
    },
    address: {
      street: 'Jl. Raya Industri No. 88',
      country: 'Indonesia',
      province: 'Jawa Tengah',
      city: 'Semarang',
      district: 'Genuk',
      subdistrict: 'Trimulyo',
      postalCode: '50144',
    },
    contact: {
      name: 'Siti Aminah',
      title: 'Madam',
      jobPosition: 'Quality',
      email: 'siti.a@kartonsejati.co.id',
      phone: '(024) 760-3346',
      mobile: '+62 818-2233-4455',
      notes: '',
    },
    profile: filledProfile({
      banking: {
          currency: 'IDR',
          setAgreementRate: 'active',
          termsOfPayment1: 'D060',
          termsOfPayment2: '',
          termsOfPayment3: '',
          fiscalPosition: 'FP04',
          lines: [
            makeBankLine({
              accountType: 'AT02',
              bankCode: 'BNI',
              accountNumber: '0889977665',
              accountHolder: 'PT Karton Sejati Abadi',
              statement: { name: 'rekening-koran.pdf', size: 480_000, type: 'application/pdf' },
            }),
          ],
        },
    }),
    consent: {
      gtcAcceptedAt: daysAgo(2),
      dataAccuracyAcceptedAt: daysAgo(2),
      acceptedBy: 'Siti Aminah',
      version: '2026.04.10',
      path: PATH.INVITE,
    },
    verification: { status: 'pending', notes: [] },
    timeline: [
      { at: daysAgo(24), label: 'Registrasi dikirim pemasok', actor: 'Siti Aminah' },
      { at: daysAgo(22), label: 'Registrasi disetujui', actor: 'Dewi Anggraini' },
      { at: daysAgo(18), label: 'Undangan portal dikirim', actor: 'Dewi Anggraini' },
      { at: daysAgo(2), label: 'Persetujuan ditandatangani pemasok', actor: 'Siti Aminah' },
    ],
  },
  {
    id: 'SUP-2026-0118',
    status: STATUS.PREFERRED,
    submittedAt: daysAgo(60),
    decidedAt: daysAgo(58),
    registeredAt: daysAgo(40),
    preferredSubmittedAt: daysAgo(20),
    preferredSubmittedBy: 'Dewi Anggraini',
    preferredDecision: {
      decision: 'approved',
      note: 'Rekam jejak mutu baik dan kualifikasi komoditas sesuai kebutuhan.',
      decidedAt: daysAgo(18),
      decidedBy: 'Lestari Handayani',
    },
    onboardingPath: PATH.INVITE,
    account: {
      accountId: 'SUP-RAW-0118',
      inviteToken: 'pgn-inv-90ac13',
      emailSentAt: daysAgo(55),
      passwordChanged: true,
    },
    general: {
      legalStatus: 'Z2',
      entityType: '0001',
      vendorName: 'PT Kimia Prima Lestari',
      vendorType: '0001',
      vendorTypeDetail: '0003',
      targetCompanies: ['Paragon Corp Indonesia'],
      otvStatus: 'C1',
      vendorDirectType: 'Z002',
      companyEmail: 'sales@kimiaprima.co.id',
      officePhone: '(021) 899-4455',
      mobilePhone: '+62 811-9900-1122',
      website: 'https://www.kimiaprima.co.id',
    },
    address: {
      street: 'Kawasan Industri Pulogadung Blok C No. 9',
      country: 'Indonesia',
      province: 'DKI Jakarta',
      city: 'Jakarta Timur',
      district: 'Cakung',
      subdistrict: 'Jatinegara',
      postalCode: '13930',
    },
    contact: {
      name: 'Hendra Wijaya',
      title: 'Mr',
      jobPosition: 'Sales',
      email: 'hendra@kimiaprima.co.id',
      phone: '(021) 899-4456',
      mobile: '+62 811-9900-1122',
      notes: '',
    },
    profile: filledProfile({
      banking: {
          currency: 'IDR',
          setAgreementRate: 'active',
          termsOfPayment1: 'D090',
          termsOfPayment2: '',
          termsOfPayment3: '',
          fiscalPosition: 'FP04',
          lines: [
            makeBankLine({
              accountType: 'AT02',
              bankCode: 'BMRI',
              accountNumber: '1220099887',
              accountHolder: 'PT Kimia Prima Lestari',
              statement: { name: 'rekening-koran.pdf', size: 480_000, type: 'application/pdf' },
            }),
          ],
        },
      contacts: [
        {
          id: 'ct-a',
          name: 'Hendra Wijaya',
          title: 'Mr',
          jobPosition: 'Sales',
          email: 'hendra@kimiaprima.co.id',
          phone: '(021) 899-4456',
          mobile: '+62 811-9900-1122',
          notes: '',
          isPrimary: true,
        },
        {
          id: 'ct-b',
          name: 'Maya Kusuma',
          title: 'Madam',
          jobPosition: 'Finance',
          email: 'maya@kimiaprima.co.id',
          phone: '(021) 899-4457',
          mobile: '+62 812-3311-4455',
          notes: 'Penanggung jawab penagihan.',
          isPrimary: false,
        },
      ],
    }),
    consent: {
      gtcAcceptedAt: daysAgo(42),
      dataAccuracyAcceptedAt: daysAgo(42),
      acceptedBy: 'Hendra Wijaya',
      version: '2026.04.10',
      path: PATH.INVITE,
    },
    verification: { status: 'verified', verifiedAt: daysAgo(40), verifiedBy: 'Dewi Anggraini', notes: [] },
    timeline: [
      { at: daysAgo(60), label: 'Registrasi dikirim pemasok', actor: 'Hendra Wijaya' },
      { at: daysAgo(58), label: 'Registrasi disetujui', actor: 'Dewi Anggraini' },
      { at: daysAgo(55), label: 'Undangan portal dikirim', actor: 'Dewi Anggraini' },
      { at: daysAgo(42), label: 'Persetujuan ditandatangani pemasok', actor: 'Hendra Wijaya' },
      { at: daysAgo(40), label: 'Dokumen lolos periksa, lanjut ke qualification', actor: 'Dewi Anggraini' },
      { at: daysAgo(20), label: 'Diajukan sebagai preferred supplier', actor: 'Dewi Anggraini' },
      { at: daysAgo(18), label: 'Ditetapkan sebagai preferred supplier', actor: 'Lestari Handayani' },
    ],
  },
];

export { emptyProfile };
