-- =====================================================================
-- 02b — Data acuan kualifikasi: UNSPSC dan negara
-- =====================================================================
-- Daftar komoditas ini adalah KURASI 42 butir yang relevan bagi manufaktur
-- kosmetik, bukan salinan UNSPSC lengkap. Daftar resmi berisi lebih dari
-- 150.000 kode yang sebagian besar tidak akan pernah dipakai Paragon;
-- menampilkan seluruhnya justru menyulitkan staf menemukan kategori yang tepat.
--
-- Kode segmen dua digit mengikuti taksonomi resmi. Kode delapan digit tiap
-- komoditas BELUM dicocokkan dengan daftar UNSPSC resmi — nomor inilah yang
-- terbawa ke sistem pengadaan dan pelaporan, jadi mintalah tim master data
-- memverifikasinya sebelum dipakai di produksi. Menambah atau mengoreksi butir
-- cukup dilakukan di sini; tidak ada kode aplikasi yang perlu berubah.
-- =====================================================================

insert into md_unspsc_segment (code, name) values
  ('10','Bahan tanaman dan hewan hidup'),
  ('11','Bahan mineral, tekstil, dan bahan nabati tak termakan'),
  ('12','Bahan kimia dan biokimia'),
  ('13','Resin, karet, busa, dan elastomer'),
  ('14','Bahan dan produk kertas'),
  ('24','Mesin penanganan dan penyimpanan bahan'),
  ('31','Komponen dan perlengkapan manufaktur'),
  ('41','Peralatan laboratorium dan pengujian'),
  ('47','Peralatan dan perlengkapan kebersihan'),
  ('50','Produk makanan dan minuman'),
  ('51','Obat dan produk farmasi'),
  ('53','Pakaian, tas, dan produk perawatan diri'),
  ('73','Jasa produksi dan manufaktur industri'),
  ('78','Jasa transportasi, penyimpanan, dan pos'),
  ('80','Jasa manajemen dan administrasi'),
  ('81','Jasa rekayasa dan riset teknologi'),
  ('82','Jasa editorial, desain, dan grafis')
on conflict(code) do update set name = excluded.name;

insert into md_unspsc_commodity (code, name, segment_code, sort_order) values
  ('12141900','Surfaktan anionik','12',1),
  ('12142000','Surfaktan nonionik','12',2),
  ('12161500','Emulsifier dan pengemulsi','12',3),
  ('12161600','Pengental dan pembentuk gel','12',4),
  ('12161700','Pengawet kosmetik','12',5),
  ('12162000','Antioksidan','12',6),
  ('12164000','Pewarna dan pigmen kosmetik','12',7),
  ('12171500','Pelarut organik','12',8),
  ('12352100','Bahan aktif perawatan kulit','12',9),
  ('10171500','Ekstrak tumbuhan','10',10),
  ('11121800','Lilin nabati dan mineral','11',11),
  ('11162100','Serat alami untuk kemasan','11',12),
  ('50151500','Minyak nabati','50',13),
  ('50151700','Lemak dan minyak terhidrogenasi','50',14),
  ('50202300','Air demineralisasi dan air proses','50',15),
  ('51102700','Vitamin dan turunannya','51',16),
  ('51241000','Bahan aktif antimikroba','51',17),
  ('53131500','Produk perawatan kulit jadi','53',18),
  ('53131600','Produk perawatan rambut jadi','53',19),
  ('53131700','Produk tata rias jadi','53',20),
  ('53131800','Produk parfum dan pewangi','53',21),
  ('13111000','Resin plastik untuk kemasan','13',22),
  ('14111500','Kertas dan karton kemasan','14',23),
  ('14111800','Label dan stiker','14',24),
  ('24111500','Botol dan wadah plastik','24',25),
  ('24111800','Tutup, pompa, dan dispenser','24',26),
  ('24112000','Wadah kaca','24',27),
  ('24121500','Tube dan sachet fleksibel','24',28),
  ('24141500','Kotak dan dus karton','24',29),
  ('31201500','Perekat dan lem kemasan','31',30),
  ('41105300','Peralatan gelas laboratorium','41',31),
  ('41115400','Instrumen analisis laboratorium','41',32),
  ('41116100','Reagen dan bahan uji','41',33),
  ('47131500','Bahan pembersih dan sanitasi','47',34),
  ('73152100','Jasa maklon dan produksi kontrak','73',35),
  ('73181100','Jasa pengemasan ulang','73',36),
  ('78101800','Jasa transportasi darat','78',37),
  ('78131600','Jasa pergudangan','78',38),
  ('80101500','Jasa konsultansi manajemen','80',39),
  ('81101500','Jasa rekayasa proses','81',40),
  ('81141600','Jasa pengujian dan sertifikasi','81',41),
  ('82141500','Jasa desain kemasan','82',42)
on conflict(code) do update set
  name = excluded.name, segment_code = excluded.segment_code;

-- Negara mengikuti ISO 3166-1 alpha-2.
insert into md_country (code, name) values
  ('AF','Afghanistan'),
  ('ZA','Afrika Selatan'),
  ('AL','Albania'),
  ('DZ','Aljazair'),
  ('US','Amerika Serikat'),
  ('AO','Angola'),
  ('SA','Arab Saudi'),
  ('AR','Argentina'),
  ('AM','Armenia'),
  ('AU','Australia'),
  ('AT','Austria'),
  ('AZ','Azerbaijan'),
  ('BH','Bahrain'),
  ('BD','Bangladesh'),
  ('NL','Belanda'),
  ('BY','Belarus'),
  ('BE','Belgia'),
  ('BT','Bhutan'),
  ('BO','Bolivia'),
  ('BA','Bosnia dan Herzegovina'),
  ('BR','Brasil'),
  ('GB','Britania Raya'),
  ('BN','Brunei Darussalam'),
  ('BG','Bulgaria'),
  ('CZ','Ceko'),
  ('CL','Cile'),
  ('DK','Denmark'),
  ('EC','Ekuador'),
  ('EE','Estonia'),
  ('ET','Etiopia'),
  ('FJ','Fiji'),
  ('PH','Filipina'),
  ('FI','Finlandia'),
  ('GE','Georgia'),
  ('GH','Ghana'),
  ('GT','Guatemala'),
  ('HK','Hong Kong'),
  ('HU','Hungaria'),
  ('IN','India'),
  ('ID','Indonesia'),
  ('IQ','Irak'),
  ('IR','Iran'),
  ('IE','Irlandia'),
  ('IS','Islandia'),
  ('IL','Israel'),
  ('IT','Italia'),
  ('JM','Jamaika'),
  ('JP','Jepang'),
  ('DE','Jerman'),
  ('KH','Kamboja'),
  ('CM','Kamerun'),
  ('CA','Kanada'),
  ('KZ','Kazakhstan'),
  ('KE','Kenya'),
  ('CO','Kolombia'),
  ('KR','Korea Selatan'),
  ('KP','Korea Utara'),
  ('CR','Kosta Rika'),
  ('HR','Kroasia'),
  ('CU','Kuba'),
  ('KW','Kuwait'),
  ('LA','Laos'),
  ('LV','Latvia'),
  ('LB','Lebanon'),
  ('LY','Libya'),
  ('LT','Lituania'),
  ('LU','Luksemburg'),
  ('MG','Madagaskar'),
  ('MK','Makedonia Utara'),
  ('MV','Maladewa'),
  ('MY','Malaysia'),
  ('MA','Maroko'),
  ('MU','Mauritius'),
  ('MX','Meksiko'),
  ('EG','Mesir'),
  ('MD','Moldova'),
  ('MN','Mongolia'),
  ('ME','Montenegro'),
  ('MZ','Mozambik'),
  ('MM','Myanmar'),
  ('NP','Nepal'),
  ('NG','Nigeria'),
  ('NO','Norwegia'),
  ('OM','Oman'),
  ('PK','Pakistan'),
  ('PA','Panama'),
  ('CI','Pantai Gading'),
  ('PG','Papua Nugini'),
  ('PY','Paraguay'),
  ('PE','Peru'),
  ('PL','Polandia'),
  ('PT','Portugal'),
  ('FR','Prancis'),
  ('QA','Qatar'),
  ('DO','Republik Dominika'),
  ('RO','Rumania'),
  ('RU','Rusia'),
  ('NZ','Selandia Baru'),
  ('SN','Senegal'),
  ('RS','Serbia'),
  ('SG','Singapura'),
  ('CY','Siprus'),
  ('SI','Slovenia'),
  ('SK','Slowakia'),
  ('ES','Spanyol'),
  ('LK','Sri Lanka'),
  ('SY','Suriah'),
  ('SE','Swedia'),
  ('CH','Swiss'),
  ('TW','Taiwan'),
  ('TZ','Tanzania'),
  ('TH','Thailand'),
  ('TL','Timor Leste'),
  ('CN','Tiongkok'),
  ('TN','Tunisia'),
  ('TR','Turki'),
  ('UG','Uganda'),
  ('UA','Ukraina'),
  ('AE','Uni Emirat Arab'),
  ('UY','Uruguay'),
  ('UZ','Uzbekistan'),
  ('VE','Venezuela'),
  ('VN','Vietnam'),
  ('YE','Yaman'),
  ('JO','Yordania'),
  ('GR','Yunani'),
  ('ZM','Zambia'),
  ('ZW','Zimbabwe')
on conflict(code) do update set name = excluded.name;
